version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Add any other configurations you might need, such as:
    # volumes:
    #   - ./data:/app/data
    # depends_on:
    #   - database
    # networks:
    #   - app-network 